device: "cuda:1"

model:
  segmentation: "facebook/sam3"
  depth_estimation: "Intel/dpt-hybrid-midas"

  # inpainting: "black-forest-labs/FLUX.1-Fill-dev"
  # controlnet_union: "InstantX/FLUX.1-dev-Controlnet-Union" 

  # controlnet_depth: "black-forest-labs/FLUX.1-Depth-dev"
  # controlnet_canny: "black-forest-labs/FLUX.1-Canny-dev"



  inpainting: "stable-diffusion-v1-5/stable-diffusion-inpainting"
  # controlnet: "lllyasviel/control_v11p_sd15_inpaint"
  # controlnet_depth: "lllyasviel/sd-controlnet-depth"
  # controlnet_canny: "lllyasviel/sd-controlnet-canny"

  # inpainting: "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"  
  # controlnet_depth: "diffusers/controlnet-depth-sdxl-1.0"
  # controlnet_canny: "diffusers/controlnet-canny-sdxl-1.0"
  # vae: "madebyollin/sdxl-vae-fp16-fix"

input:
  project_path: "/home/SImany/data_generation_pipeline"
  image_folder: "images/"
  image_name: "4.jpg"
  prompt_seg: "buildings"

  prompt_inpaint: "remove the building"
  negative_prompt_inpaint: ""

  # prompt_inpaint: 
  #   - "photorealistic street view, realistic urban scene, "
  #   - "consistent perspective, natural lighting, high detail "
  #   - remove the building and fill the region with plausible background continuation "
  #   - "(sky, distant buildings, trees) matching the surrounding context"

  # negative_prompt_inpaint: 
  #   - "cartoon, painting, unrealistic, blurry, low resolution, "
  #   - "warped geometry, bent lines, duplicate windows, repeated patterns, "
  #   - "text, watermark, logo, artifacts, oversharpen, halo, seams"
  

  canny: false
  depth: false
  inpaint: false # only for stable diffusion inpainting

output:
  segmentation_overlay: "results/segmentation_overlay/"
  inpainting_results: "results/inpainting/"
  panorama_to_perspective: "results/panorama_to_perspective/"
  stitching_results: "results/stitching/"
  edge_detection_results: "results/edge_detection/"
  red_herring_results: "results/red_herring/"
  depth_results: "results/depth/"
  inpaited_only_results: "results/inpainted_only/"


hydra:
  job_logging:
    loggers:
      httpx:
        level: WARNING
