device: "cuda:1"

model:
  segmentation: "facebook/sam3"
  depth_estimation: "Intel/dpt-hybrid-midas"

  # inpainting: "black-forest-labs/FLUX.1-Fill-dev" #options: "black-forest-labs/FLUX.1-Fill-dev", "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
  
  # inpainting: "stable-diffusion-v1-5/stable-diffusion-inpainting"
  # controlnet: "lllyasviel/control_v11p_sd15_inpaint"
  # controlnet_depth: "lllyasviel/sd-controlnet-depth"
  # controlnet_canny: "lllyasviel/sd-controlnet-canny"

  # inpainting: "stabilityai/stable-diffusion-xl-base-1.0"
  inpainting: "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"  
  controlnet_depth: "diffusers/controlnet-depth-sdxl-1.0"
  controlnet_canny: "diffusers/controlnet-canny-sdxl-1.0"
  vae: "madebyollin/sdxl-vae-fp16-fix"

input:
  image_folder: "/home/SImany/data_generation_pipeline/images/"
  image_name: "7.jpg"
  prompt_seg: "cracks"

  prompt_inpaint: ""
  negative_prompt_inpaint: ""

  # prompt_inpaint: 
  #   - "photorealistic street view, realistic urban scene, "
  #   - "consistent perspective, natural lighting, high detail "
  #   - remove the building and fill the region with plausible background continuation "
  #   - "(sky, distant buildings, trees) matching the surrounding context"

  # negative_prompt_inpaint: 
  #   - "cartoon, painting, unrealistic, blurry, low resolution, "
  #   - "warped geometry, bent lines, duplicate windows, repeated patterns, "
  #   - "text, watermark, logo, artifacts, oversharpen, halo, seams"
  

  canny: true
  depth: true
  inpaint: false

output:
  segmentation_overlay: "/home/SImany/data_generation_pipeline/results/segmentation_overlay/"
  inpainting_results: "/home/SImany/data_generation_pipeline/results/inpainting/"
  panorama_to_perspective: "/home/SImany/data_generation_pipeline/results/panorama_to_perspective/"
  stitching_results: "/home/SImany/data_generation_pipeline/results/stitching/"
  edge_detection_results: "/home/SImany/data_generation_pipeline/results/edge_detection/"
  red_herring_results: "/home/SImany/data_generation_pipeline/results/red_herring/"
  depth_results: "/home/SImany/data_generation_pipeline/results/depth/"
  inpaited_only_results: "/home/SImany/data_generation_pipeline/results/inpainted_only/"


hydra:
  job_logging:
    loggers:
      httpx:
        level: WARNING
